thisishome/config/routes.rb
Rails.application.routes.draw do
  get 'awards/show'

  get 'screenshots/show'

  root 'welcome#landingpage'

  get 'screenings/show'

  get 'about/show'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

thisishome/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

thisishome/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

thisishome/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

thisishome/app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  def show
  end
end

thisishome/app/controllers/screenings_controller.rb
class ScreeningsController < ApplicationController
  def show
  end
end

thisishome/app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController
  def show
  end
end

thisishome/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def landingpage
  end
end

thisishome/app/helpers/about_helper.rb
module AboutHelper
end

thisishome/app/helpers/application_helper.rb
module ApplicationHelper
end

thisishome/app/helpers/awards_helper.rb
module AwardsHelper
end

thisishome/app/helpers/screenings_helper.rb
module ScreeningsHelper
end

thisishome/app/helpers/screenshots_helper.rb
module ScreenshotsHelper
end

thisishome/app/helpers/welcome_helper.rb
module WelcomeHelper
end

thisishome/app/views/about/show.html.erb
<div class="jumbotron jumbotron-fluid" style="background: linear-gradient(90deg, #cb2d3e, #a73737) !important; margin-bottom: 0px !important; font-weight: strong !important;">
  <div class="container well well-lg" style="background: linear-gradient(90deg, #cb2d3e, #a73737); border: 0px solid #e3e3e3 !important;">
    <h1>Logline:</h1>
      <h3> When wildfires tore through the city Fort McMurray in spring of 2016, filmmaker Var Bhalla's first response was to grab his camera and get on a plane. Returning to his hometown after the devastating fire forced the evacuation of over 90,000 residents, Bhalla captures a community in flux. Struggling with loss and the immensity of the trauma, Bhalla brings us into the community by introducing a wide range of characters, each struggling with the challenges the fire has brought into their lives. </h3>
  </div>
</div>
<div class="jumbotron jumbotron-fluid" style="background: linear-gradient(90deg, #cb2d3e, #a73737) !important; margin-bottom: 0px !important; font-weight: strong !important;">
  <div class="container well well-lg" style="background: linear-gradient(90deg, #cb2d3e, #a73737); border: 0px solid #e3e3e3 !important;">
    <h1>Storyline:</h1>
      <h3> This is not just a story about devastation. It's not a story about tragedy, oil, or the environment. This is a story about how a husband and wife immigrated from India to Northern Alberta to start a new life. It's a story about the different people that came to call Fort McMurray home and how 30 years after the filmmaker was born there, his home-town almost burned to the ground. From the ashes of one of the worst natural disasters in Canadian history, this documentary explores the restoration of hope in a community that faced tragedy and devastation. Var Bhalla (narrator and guiding character) returns to his hometown after 'the Beast' ravaged the city.</h3>
  </div>
</div>

thisishome/app/views/awards/show.html.erb
<div class="jumbotron jumbotron-fluid" style="background: linear-gradient(90deg, #cb2d3e, #a73737) !important; margin-bottom: 0px !important; font-weight: strong !important;">
  <div class="container well well-lg" style="background: linear-gradient(90deg, #cb2d3e, #a73737); border: 0px solid #e3e3e3 !important;">
    <h1>Awards:</h1>
    <br><br>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
          <%= image_tag("laurels/File_000.png", class: "img-responsive") %> <br>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <%= image_tag("laurels/newwest.png", class: "img-responsive") %> <br>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <%= image_tag("laurels/creation.png", class: "img-responsive") %> <br>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <%= image_tag("laurels/cinemaworld.png", class: "img-responsive") %> <br>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <%= image_tag("laurels/directorscut.png", class: "img-responsive") %> <br>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <%= image_tag("laurels/durham.png", class: "img-responsive") %> <br>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
          <%= image_tag("laurels/airdrie.png", class: "img-responsive") %> <br>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
          <%= image_tag("laurels/ftmac.png", class: "img-responsive") %> <br>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
          <%= image_tag("laurels/regina.png", class: "img-responsive") %> <br>
      </div>
  </div>
</div>

thisishome/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>This Is Home Documentary Film</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "#thisishomedoc", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li> <a href=""> <i class="fa fa-film fa-inverse fa-2x" aria-hidden="true"></i> </a> </li>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', about_show_path %></li>
          <li><%= link_to 'Awards', awards_show_path %></li>
          <li><%= link_to 'Screenings', screenings_show_path %></li>
          <li><%= link_to 'Screenshots', screenshots_show_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="https://Facebook.com/redlinemedialive " class="fa fa-facebook fa-2x"></a>
          </li>
          <li>
            <a href="https://twitter.com/redlinemediainc?lang=en" <%= fa_icon 'twitter inverse 2x' %> </a>
          </li>
          <li>
            <a href="https://www.instagram.com/red.line.media/" class="fa fa-instagram fa-2x"></a>
          </li>
          <li>  <div id="bm"> </div> </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>
  </div>
    <%= yield %>
    <!-- Scripts -->
    <script src="/javascripts/navbarhide.js" type="text/javascript"></script>
    <script src="javascripts/bodymovin.js"></script>
    <script src="javascripts/application.js"></script>
</body>
</html>

thisishome/app/views/screenings/show.html.erb
<div class="jumbotron jumbotron-fluid" style="background: linear-gradient(90deg, #cb2d3e, #a73737) !important; margin-bottom: 0px !important; font-weight: strong !important;">
  <div class="container well well-lg" style="background: linear-gradient(90deg, #cb2d3e, #a73737); border: 0px solid #e3e3e3 !important;">
    <h1> Past Screenings:</h1>
      <h3 style="font-weight: bold">  May 23, 2017  </h3>
        <h3> Premiere Screening, Keyano Theatre | Fort McMurray, AB </h3>
      <h3 style="font-weight: bold">  August 17, 2017 </h3>
        <h3> Regina International Film Festival, Cineplex Odeon Southland Mall | Regina, SK </h3>
      <h3 style="font-weight: bold">  September 23, 2017 </h3>
        <h3> Airdrie Film Festival, Town Country Centre | Airdrie, AB </h3>
      <h3 style="font-weight: bold">  September 24 </h3>
        <h3> Durham Region International Film Festival, Regent Theatre | Oshawa, ONT </h3>
      <h1> Upcoming :</h1>
        <h3 style="font-weight: bold">  October 20, 2017 </h3>
          <h3> NewWest Film Festival, Landmark Cinemas 10 | New Westminster, BC </h3>
        <h3 style="font-weight: bold">  November 12, 2017 </h3>
          <h3> Fort McMurray International Film Festival, Suncor Energy Centre | Fort McMurray, AB </h3>
  </div>
</div>

thisishome/app/views/screenshots/show.html.erb
<div class="container" style="padding-top: 13px;">
    <div class="row imagetiles">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/bhallas.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/chuch1.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/city1.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/city2.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/City3.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/devastation1.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/devastation3.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/fire2.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/fire3.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/firefighter1.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/firefighter2.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/FortMacStrong.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/harvey1.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/harvey2.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/mrbarr.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/paint1.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/parade3.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/plane1.jpg", class: "img-responsive") %> <br>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= image_tag("hd_stills/Productionshot.jpg", class: "img-responsive") %> <br>
        </div>
    </div>
</div>

thisishome/app/views/welcome/landingpage.html.erb
<div class="full-width-image">
  <%= image_tag("this_is_home_horizantal_laurels.jpg", class: "img-responsive") %>
</div>
<div class="jumbotron jumbotron-fluid" style="background: linear-gradient(90deg, #cb2d3e, #a73737) !important; margin-bottom: 0px !important; font-weight: strong !important;">
  <div class="container well well-lg" style="background: linear-gradient(90deg, #cb2d3e, #a73737); border: 0px solid #e3e3e3 !important;">
    <h1>THIS IS NOT JUST A STORY ABOUT: </h1>
      <h3> DEVASTATION </h3>
      <h3> TRAGEDY </h3>
      <h3> LOSS </h3>
      <h3> OIL </h3>
  </div>
</div>
  <div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ncAA4h60Cvw?rel=0" frameborder="0" allowfullscreen></iframe></iframe>
  </div>